-- BigQuery Standard SQL
-- Looker Studio friendly views for the OudSeed v0.1 dashboard.
--
-- These views keep raw table storage separate from reporting semantics.
-- Ratio metrics are recalculated from aggregated numerators/denominators
-- so Looker Studio charts do not average row-level rates by mistake.

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_ads_ad_daily` AS
SELECT
  date,
  workspace_id,
  client_id,
  platform,
  account_id,
  account_name,
  campaign_id,
  campaign_name,
  ad_group_id,
  ad_group_name,
  ad_id,
  ad_name,
  impressions,
  clicks AS link_clicks,
  spend,
  conversions,
  conversion_value,
  add_to_cart,
  purchase,
  purchase_value,
  cost_per_add_to_cart,
  cost_per_purchase,
  outbound_clicks,
  page_engagement,
  post_engagement,
  post_reactions,
  post_comments,
  post_saves,
  post_shares,
  SAFE_DIVIDE(clicks, impressions) AS ctr,
  SAFE_DIVIDE(spend, clicks) AS cpc,
  SAFE_DIVIDE(spend * 1000, impressions) AS cpm,
  SAFE_DIVIDE(spend, conversions) AS cpa,
  SAFE_DIVIDE(conversion_value, spend) AS roas,
  currency,
  source_updated_at,
  created_at,
  updated_at
FROM `oudseed.ads_pipeline.unified_ads_daily`;

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_ads_campaign_daily` AS
SELECT
  date,
  workspace_id,
  client_id,
  platform,
  account_id,
  ANY_VALUE(account_name) AS account_name,
  campaign_id,
  ANY_VALUE(campaign_name) AS campaign_name,
  SUM(impressions) AS impressions,
  SUM(clicks) AS link_clicks,
  SUM(spend) AS spend,
  SUM(conversions) AS conversions,
  SUM(conversion_value) AS conversion_value,
  SUM(add_to_cart) AS add_to_cart,
  SUM(purchase) AS purchase,
  SUM(purchase_value) AS purchase_value,
  SAFE_DIVIDE(SUM(spend), SUM(add_to_cart)) AS cost_per_add_to_cart,
  SAFE_DIVIDE(SUM(spend), SUM(purchase)) AS cost_per_purchase,
  SUM(outbound_clicks) AS outbound_clicks,
  SUM(page_engagement) AS page_engagement,
  SUM(post_engagement) AS post_engagement,
  SUM(post_reactions) AS post_reactions,
  SUM(post_comments) AS post_comments,
  SUM(post_saves) AS post_saves,
  SUM(post_shares) AS post_shares,
  SAFE_DIVIDE(SUM(clicks), SUM(impressions)) AS ctr,
  SAFE_DIVIDE(SUM(spend), SUM(clicks)) AS cpc,
  SAFE_DIVIDE(SUM(spend) * 1000, SUM(impressions)) AS cpm,
  SAFE_DIVIDE(SUM(spend), SUM(conversions)) AS cpa,
  SAFE_DIVIDE(SUM(conversion_value), SUM(spend)) AS roas,
  ANY_VALUE(currency) AS currency,
  MAX(updated_at) AS updated_at
FROM `oudseed.ads_pipeline.unified_ads_daily`
GROUP BY
  date,
  workspace_id,
  client_id,
  platform,
  account_id,
  campaign_id;

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_ads_campaign_weekly` AS
SELECT
  week_start_date,
  week_end_date,
  workspace_id,
  client_id,
  platform,
  account_id,
  account_name,
  campaign_id,
  campaign_name,
  impressions,
  clicks AS link_clicks,
  spend,
  conversions,
  conversion_value,
  add_to_cart,
  purchase,
  purchase_value,
  cost_per_add_to_cart,
  cost_per_purchase,
  outbound_clicks,
  page_engagement,
  post_engagement,
  post_reactions,
  post_comments,
  post_saves,
  post_shares,
  ctr,
  cpc,
  cpm,
  cpa,
  roas,
  previous_week_spend,
  previous_week_clicks AS previous_week_link_clicks,
  previous_week_conversions,
  previous_week_add_to_cart,
  previous_week_purchase,
  previous_week_cpc,
  previous_week_cpa,
  previous_week_roas,
  spend_wow,
  clicks_wow AS link_clicks_wow,
  conversions_wow,
  add_to_cart_wow,
  purchase_wow,
  cpc_wow,
  cpa_wow,
  roas_wow,
  spend_wow_rate,
  clicks_wow_rate AS link_clicks_wow_rate,
  conversions_wow_rate,
  add_to_cart_wow_rate,
  purchase_wow_rate,
  cpc_wow_rate,
  cpa_wow_rate,
  roas_wow_rate,
  updated_at
FROM `oudseed.ads_pipeline.weekly_performance_summary`;

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_ads_campaign_monthly` AS
SELECT
  month_start_date,
  month_end_date,
  workspace_id,
  client_id,
  platform,
  account_id,
  account_name,
  campaign_id,
  campaign_name,
  impressions,
  clicks AS link_clicks,
  spend,
  conversions,
  conversion_value,
  add_to_cart,
  purchase,
  purchase_value,
  cost_per_add_to_cart,
  cost_per_purchase,
  outbound_clicks,
  page_engagement,
  post_engagement,
  post_reactions,
  post_comments,
  post_saves,
  post_shares,
  ctr,
  cpc,
  cpm,
  cpa,
  roas,
  previous_month_spend,
  previous_month_clicks AS previous_month_link_clicks,
  previous_month_conversions,
  previous_month_add_to_cart,
  previous_month_purchase,
  previous_month_cpc,
  previous_month_cpa,
  previous_month_roas,
  spend_mom,
  clicks_mom AS link_clicks_mom,
  conversions_mom,
  add_to_cart_mom,
  purchase_mom,
  cpc_mom,
  cpa_mom,
  roas_mom,
  spend_mom_rate,
  clicks_mom_rate AS link_clicks_mom_rate,
  conversions_mom_rate,
  add_to_cart_mom_rate,
  purchase_mom_rate,
  cpc_mom_rate,
  cpa_mom_rate,
  roas_mom_rate,
  updated_at
FROM `oudseed.ads_pipeline.monthly_performance_summary`;

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_sync_status` AS
SELECT
  sync_id,
  workspace_id,
  client_id,
  platform,
  account_id,
  sync_start_date,
  sync_end_date,
  status,
  rows_fetched,
  rows_inserted,
  error_message,
  attribution_setting,
  timezone_setting,
  scheduler_timezone,
  started_at,
  finished_at,
  TIMESTAMP_DIFF(finished_at, started_at, SECOND) AS duration_seconds
FROM `oudseed.ads_pipeline.sync_logs`;

CREATE OR REPLACE VIEW `oudseed.ads_pipeline.vw_looker_ai_report_logs` AS
SELECT
  report_id,
  workspace_id,
  client_id,
  report_type,
  week_start_date AS period_start_date,
  week_end_date AS period_end_date,
  model_name,
  status,
  error_message,
  report_text,
  LENGTH(report_text) AS report_text_chars,
  created_at
FROM `oudseed.ads_pipeline.ai_report_logs`;
